PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT DISTINCT ?character ?characterLabel ?property ?propertyLabel ?value ?valueLabel
WHERE {
  VALUES ?character {
    wd:Q477948  # Monkey D. Luffy
    wd:Q931     # Naruto Uzumaki
    wd:Q843545  # Light Yagami
  }

  ?character ?property ?value .

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,it".
  }
}
ORDER BY ?characterLabel ?propertyLabel
LIMIT 300
