PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
 
SELECT DISTINCT ?item ?itemlabel ?proprieta ?proprietalabel ?valore ?valorelabel
WHERE {
 
 # 1. Definiamo i nodi di partenza specifici tramite i loro ID
 VALUES ?item { wd:Q25929253 wd:Q26971382 wd:Q642 }
 
 # 2. Troviamo le relazioni e i valori
 ?item ?uriProprieta ?valore .
 ?proprieta wikibase:directClaim ?uriProprieta .
 
 # 3. Estraiamo MANUALMENTE la label della proprietà
 OPTIONAL {
   ?proprieta rdfs:label ?proprietalabel .
   FILTER(LANG(?proprietalabel) = "en")
 }
 
 # 4. Estraiamo MANUALMENTE la label del valore
 OPTIONAL {
   ?valore rdfs:label ?valorelabel .
   FILTER(LANG(?valorelabel) = "en")
 }
 
 # 5. Estraiamo MANUALMENTE la label dell'item
 OPTIONAL {
   ?item rdfs:label ?itemlabel .
   FILTER(LANG(?itemlabel) = "en")
 }
}
