PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?stockCharacter ?stockCharacterLabel ?description
WHERE {
  ?stockCharacter wdt:P31 wd:Q636497 . # stock character

  OPTIONAL {
    ?stockCharacter schema:description ?description .
    FILTER(LANG(?description) = "en")
  }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,it". }
}
ORDER BY ?stockCharacterLabel
