PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT DISTINCT ?personaggioLabel ?operaLabel ?tipoLabel  ?stockCharacterLabel
WHERE {
  # 1. Definiamo l'elenco delle opere target
  VALUES ?opera { 
    wd:Q4431905 wd:Q642 wd:Q673 wd:Q104623150 wd:Q1834 
    wd:Q26971382 wd:Q28667972 wd:Q718624 wd:Q710324 wd:Q25929253 
  } 
  
  # 2. Trova i personaggi che compaiono in queste opere
    ?opera wdt:P674 ?personaggio .
  
  # 3. UNION: Estraiamo la caratteristica e la chiamiamo ?stockCharacter in ENTRAMBI i rami
  {
    # Ramo A
    ?personaggio wdt:P31 ?stockCharacter .
    ?stockCharacter wdt:P31 wd:Q1089201 .
  }
  UNION
  {
    # Ramo B 
    ?personaggio wdt:P9071 ?tipo .
  }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}